-- 코드를 입력하세요
SELECT PRD.PRODUCT_ID, PRD.PRODUCT_NAME, SUM(PRD.PRICE * ORD.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS PRD
JOIN FOOD_ORDER as ORD ON PRD.PRODUCT_ID = ORD.PRODUCT_ID
WHERE DATE_FORMAT(ORD.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRD.PRODUCT_ID ASC
;