SELECT  RES.HISTORY_ID, 
        ROUND(IF(RES.DISCOUNT_RATE IS NULL, RES.DAILY_FEE * RES.DATE_DIFF, 
                 RES.DAILY_FEE * RES.DATE_DIFF * (100-RES.DISCOUNT_RATE)*0.01),0) AS FEE
FROM  
(
        SELECT  CAR.*
                , HISTORY.HISTORY_ID
                , DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) + 1 AS DATE_DIFF
                , DISCOUNT.DISCOUNT_RATE
          FROM  CAR_RENTAL_COMPANY_CAR CAR
          LEFT
          JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
            ON  CAR.CAR_ID = HISTORY.CAR_ID
          LEFT
          JOIN  CAR_RENTAL_COMPANY_DISCOUNT_PLAN DISCOUNT
            ON  CASE WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) BETWEEN 7 AND 29 
                            THEN DISCOUNT.PLAN_ID = 10
                     WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) BETWEEN 30 AND 89 
                            THEN DISCOUNT.PLAN_ID = 11
                     WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE) >= 90 
                            THEN DISCOUNT.PLAN_ID = 12 END
         WHERE  CAR.CAR_TYPE = '트럭'
) RES 
ORDER BY FEE DESC, HISTORY_ID DESC;