-- 코드를 입력하세요
-- 정답 맞추고, 왜 그렇게 했는지 설명해줘야 함.

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF
JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
GROUP BY FIRST_HALF.FLAVOR
ORDER BY SUM(FIRST_HALF.TOTAL_ORDER + JULY.TOTAL_ORDER) DESC
LIMIT 3
;